spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
      routes:
        - id: city-service
          uri: lb://city-service
          predicates:
            - Path=/CITY-SERVICE/**
          filters:
            - RewritePath=/CITY-SERVICE/(?<path>.*), /$\{path}
        - id: weather-service
          uri: lb://weather-service
          predicates:
            - Path=/WEATHER-SERVICE/**
          filters:
            - RewritePath=/WEATHER-SERVICE/(?<path>.*), /$\{path}
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        register: false
        registerHealthCheck: false
      retry:
        enabled: true
        initialInterval: 2
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
server:
  port: ${PORT:8080}
